### ISSUE TITLE
Token authentication does not work on /me endpoint

### ISSUE THREAD

**Issue by esra-aydemir** [bounswe/bounswe2017group5#190]
## About
As the title suggests.

## Visuals
![a](https://user-images.githubusercontent.com/9717121/34308460-89c3ca86-e75e-11e7-9e1b-bd4ad10eb66e.png)

**Comment by Morgazipa** [comment]
At first;  tried to reproduce the issue locally, but could not succeed. However, when trying it with our deployed endpoint 35.177.96.220 I realized that it was the case. Since I currently don't have access to the deployed code, I need help from @triforce930.  Is the solution [here](https://stackoverflow.com/questions/30151833/token-authentication-does-not-work-in-production-on-django-rest-framework) also relevant for our case?

**Comment by karacasoft** [comment]
> Is the solution here also relevant for our case?

Yes, this is exactly the solution I have used. And it works now. Thanks a lot for the research. This is resolved now,...
